spring:
  application:
    name: betterreads
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: Iv1.a9958b0f68563669
            client-secret: 41655317cc2302b59792654751682e7e6e2817cd
  data:
    cassandra:
      keyspace-name: main
      username: ravikiranravella6@gmail.com
      password: ravikiran26
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s



datastax.astra:
    secure-connect-bundle: secure-connect.zip


astra.db:
    id: a9bbac6a-85b4-44bd-8f56-4289107ee9b6
    region: us-west1
    keyspace: main
    application.token: AstraCS:lkxYZbvfGxNffEhWqCxiZjzL:66d7b0087587ea5a761778c1fe4d5ac4fed91db4f21817d88dbec4e2641b79f4
